version: '3'

services:

  api:
    build:
      context: ./cards-110-api
    restart: always
    ports: 
      - 8080:8080
    depends_on:
      - mongodb
      - redis
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE_NAME=cards-110
      - PASSWORD_ENCODER_SEED=password
      - JWT_SECRET=password
      - SPRING_PROFILES=primary,dev
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - SENDGRID_API_KEY=YOUR API KEY GOES HERE
      - PLAYER_LOGIN_URL=http://localhost:8080/#/autologin
      - CORS_WHITELIST=http://localhost:3000
      - SCORING_THRESHOLD_LOWER=0f
      - SCORING_THRESHOLD_UPPER=2.4f
      - CLOUDINARY_URL=YOUR URL GOES HERE
      - REDIS_URL=redis://h:password@redis:6379

  frontend:
    build:
      context: ./cards-110-frontend
      args:
        - NODE_ENV=development
    ports:
      - 3000:80
    volumes:
      - frontend_node_modules:/opt/app/node_modules
      - ./cards-110-frontend:/opt/app
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - PORT=80

  redis:
    image: redis:alpine
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  mongodb:
    image: mongo:4.0-xenial
    expose:
      - 27017
  
volumes:
  frontend_node_modules: