version: "3.5"

services:

  frontend:
    image: daithihearn/cards-110-frontend
    container_name: frontend
    restart: always
    env_file: frontend.env
    ports:
      - 3000:80
    networks:
      - cards
  
  api:
    image: daithihearn/cards-110-api
    container_name: api
    restart: always
    ports:
      - 8080:8080
    env_file: api.env
    networks:
      - cards
      - database

  websocket-service:
    image: daithihearn/cards-110-websocket-service
    container_name: websocket-service
    restart: always
    ports:
      - 7070:8080
    env_file: ws.env
    networks:
      - cards
      - database

  redis:
    image: bitnami/redis:7.0
    container_name: redis
    restart: always
    env_file: redis.env
    ports:
      - 6379:6379
    networks:
      - cards

networks:
  cards:
    driver: bridge
    name: cards
  database:
    external: true
    name: database
