version: '3.5'

services:

  api:
    image: localhost:5000/cards-110-api
    restart: always
    ports: 
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongodb:27017/cards-110
      - PASSWORD_ENCODER_SEED=password
      - JWT_SECRET=password
      - SPRING_PROFILES=primary,dev
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - SENDGRID_API_KEY=YOUR API KEY GOES HERE
      - PLAYER_LOGIN_URL=http://localhost:8080/#/autologin
      - CORS_WHITELIST=http://localhost:3000
    networks:
      - cards

  frontend:
    image: localhost:5000/cards-110-frontend
    restart: always
    ports:
      - 3000:5000
    networks: 
      - cards


  mongodb:
    image: mongo:4.2
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017
    networks: 
      - cards

volumes:
  mongo_data:
    driver: local

networks:
  cards:
    driver: bridge
    name: cards