version: '3.5'

services:

  api:
    image: localhost:5000/cards-110-api
    restart: always
    ports: 
      - 8080:8080
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongo-node1:27017,mongo-node2:27018,mongo-node3:27019/cards-110
      - SPRING_PROFILES=mongo-auth-password
      - SENDGRID_API_KEY=YOUR API KEY GOES HERE
      - PLAYER_LOGIN_URL=http://localhost:3000/#/autologin
      - CORS_WHITELIST=http://localhost:3000
      - AUTH0_AUDIENCE=http://localhost:8080
      - AUTH0_CLIENT_ID=https://summer-brook-3375.eu.auth0.com/
      - MONGODB_CLIENT_CERT=
      - MONGODB_CLIENT_CERT_KEY=
      - MONGODB_CA_CERT=
      - MONGODB_CLIENT_COMMON_NAME=
    networks:
      - cards
      - database

  frontend:
    image: localhost:5000/cards-110-frontend
    restart: always
    environment:
      - PORT=80
    ports:
      - 3000:80
    networks: 
      - cards

volumes:
  mongo_data:
    driver: local

networks:
  cards:
    driver: bridge
    name: cards
  database:
    external:
      name: database