version: '3.5'

services:
  mongo-setup:
    container_name: mongo-setup
    image: mongo:4.2
    volumes:
      - ./scripts:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/setup.sh", "mongo-node1", "mongo-node2",  "mongo-node3" ]
    networks:
      - database

networks:
  database:
    external:
      name: database