version: '3.5'

services:
  mongo-node1:
    hostname: mongo-node1
    container_name: mongo-node1
    image: mongo:5
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo-data-1:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 128m
    networks:
      - database

  mongo-node2:
    hostname: mongo-node2
    container_name: mongo-node2
    image: mongo:5
    expose:
      - 27018
    ports:
      - 27018:27018
    restart: always
    volumes:
      - mongo-data-2:/data/db
    entrypoint: [ "/usr/bin/mongod", "--port", "27018", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 128m
    networks:
      - database

  mongo-node3:
    hostname: mongo-node3
    container_name: mongo-node3
    image: mongo:5
    expose:
      - 27019
    ports:
      - 27019:27019
    restart: always
    volumes:
      - mongo-data-3:/data/db
    entrypoint: [ "/usr/bin/mongod", "--port", "27019", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 128m
    networks:
      - database

networks:
  database:
    driver: bridge
    name: database

volumes:
  mongo-data-1:
  mongo-data-2:
  mongo-data-3:
