version: "3.5"

services:
  redis:
    image: bitnami/redis:6.0
    container_name: redis
    restart: always
    environment:
      - REDIS_PASSWORD=password
      - REDIS_AOF_ENABLED=no
    ports:
      - 6379:6379
    networks:
      - redis

networks:
  redis:
    driver: bridge
    name: redis
